CREATE EXTERNAL LOCATION IF NOT EXISTS __FORMULA1_INCR_EXTERNAL_LOCATION__
URL '__FORMULA1_INCR_STORAGE_URL__'
WITH (STORAGE CREDENTIAL `__STORAGE_CREDENTIAL_NAME__`)
COMMENT 'External location for the incremental Formula1 container';

CREATE CATALOG IF NOT EXISTS __FORMULA1_INCR_CATALOG__
MANAGED LOCATION '__FORMULA1_INCR_STORAGE_URL__'
COMMENT 'Incremental catalog for the Formula1 project';

CREATE SCHEMA IF NOT EXISTS __FORMULA1_INCR_CATALOG__.landing;

CREATE SCHEMA IF NOT EXISTS __FORMULA1_INCR_CATALOG__.bronze
MANAGED LOCATION '__FORMULA1_INCR_STORAGE_URL__/bronze';

CREATE SCHEMA IF NOT EXISTS __FORMULA1_INCR_CATALOG__.silver
MANAGED LOCATION '__FORMULA1_INCR_STORAGE_URL__/silver';

CREATE SCHEMA IF NOT EXISTS __FORMULA1_INCR_CATALOG__.gold
MANAGED LOCATION '__FORMULA1_INCR_STORAGE_URL__/gold';

CREATE SCHEMA IF NOT EXISTS __FORMULA1_INCR_CATALOG__.control;

CREATE EXTERNAL VOLUME IF NOT EXISTS __FORMULA1_INCR_CATALOG__.landing.__LANDING_VOLUME_NAME__
LOCATION '__FORMULA1_INCR_STORAGE_URL__/landing';
